name: Keep Proxy Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the proxy
        run: |
          curl -I https://https://odoo-proxy-server-final.onrender.com/ping || echo "Proxy not reachable"
